version: '3.1'
services:
  coffee-shop-orders:
    build: coffee-shop-orders
    image: coffee-shop-orders
    container_name: coffee-shop-orders
    ports:
      - "8080:8080"
    depends_on:
      - cso-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cso-db:5432/cso
      - SPRING_DATASOURCE_USER=cso-owner
      - SPRING_DATASOURCE_PASSWORD=cso-owner
    restart: on-failure

  cso-db:
    image: postgres:14-alpine
    container_name: cso-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=cso
      - POSTGRES_USER=cso-owner
      - POSTGRES_PASSWORD=cso-owner
    restart: on-failure