CREATE TABLE IF NOT EXISTS events
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id VARCHAR NOT NULL,
    version  BIGINT NOT NULL,
    status   VARCHAR NOT NULL,
    state    TEXT  NOT NULL,
    UNIQUE (order_id, version)
);